version: "3"

services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/app/
    command: /bin/bash -c "python3 /app/manage.py runserver 0.0.0.0:8000"
