version: "3"
services:
  web:
    image: python:3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DB_ENGINE: sqlite3
      DJANGO_DB_NAME: /app/db.sqlite3
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    # Décommentez cette ligne pour désactiver le conteneur PostgreSQL (facultatif).
    # stop_signal: SIGINT
